#!/bin/bash
docker compose up -d --build
echo ""
echo "========================================"
echo "Desktop started!"
echo "========================================"
echo "SSH:     ssh temple@localhost -p 10022"
echo "Web:     https://localhost:16901"
echo "User:    temple"
echo "Password: temple"
echo ""
echo "⚠️  SECURITY: Change default passwords!"
echo "   docker exec -it temple-desktop vncpasswd"
echo "   docker exec -it temple-desktop sh -c 'echo temple:新密码 | chpasswd'"
echo "========================================"
